
before_install:
    - openssl aes-256-cbc -K $encrypted_766aa190bafb_key -iv $encrypted_766aa190bafb_iv -in deploy-key.enc -out deploy-key -d
    - chmod 600 deploy-key
    - mv deploy-key ~/.ssh/id_rsa

script: true

after_success:
    - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.4 bash)"
    - export GOPATH=$HOME/gopath
    - go get -d github.com/libgit2/git2go
    - cd $GOPATH/src/github.com/libgit2/git2go
    - git checkout next
    - git submodule update --init
    - make install
    - go get github.com/splitsh/lite
    - echo $PATH
    - go build -o splitsh-lite github.com/splitsh/lite
    - SHA1=`./splitsh-lite --prefix=modules/mod_ginger_rdf/`
    - git push git@github.com:ddeboer/mod_ginger_rdf.git $SHA1:master
