version: '2'

services:
    postgres:
        image: postgres:9.5.5-alpine
        environment:
            POSTGRES_USER: zotonic
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./data:/data
        working_dir: /data

    elasticsearch:
        image: elasticsearch:5.0
        ports:
            - 9200:9200
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:5.0
        links:
            - elasticsearch
        ports:
            - 5601:5601

    zotonic:
        image: driebit/ginger-dev:0.x
        privileged: true
        links:
            - postgres
            - elasticsearch
        volumes:
            - ./modules:/opt/zotonic/user/modules
            - ./sites:/opt/zotonic/user/sites
            - ./skel:/opt/zotonic/priv/skel/ginger
        ports:
            - 80:8000
        environment:
            MAKE: "true"
            LOGSTASH_HOST: "localhost"
            LOGSTASH_PORT: 5514

volumes:
    postgres-data: {}
    elasticsearch-data: {}
