version: '2'

services:
    postgres:
        image: postgres:9.5
        environment:
            POSTGRES_USER: zotonic
        volumes:
            - ./data:/data
        working_dir: /data

    zotonic:
        image: driebit/zotonic:0.x-dev
        privileged: true
        links:
            - postgres
        volumes:
            - ./modules:/opt/zotonic/user/modules
            - ./sites:/opt/zotonic/user/sites
        ports:
            - 8000:8000
        environment:
            MAKE: "true"

    haproxy:
        image: driebit/ginger-haproxy
        links:
            - zotonic
        ports:
            - 80:80
            - 443:443
        environment:
            - BACKEND_SERVER=zotonic
            - BACKEND_PORT=8000
