swagger: "2.0"
info:
    title: "Ginger REST API documentation"
    description: "Documentation for the Ginger REST API"
    version: "0.2"

host: DOMAIN
basePath: "/data"
schemes:
    - http
    - https

definitions:
    Resource:
        type: object
        # http://docs.zotonic.com/en/0.x/ref/models/model_rsc.html#model-rsc
        properties:
            id:
                type: integer
                example: 42
            title:
                $ref: '#/definitions/Translation'
            body:
                $ref: '#/definitions/Translation'
            summary:
                $ref: '#/definitions/Translation'
            publication_date:
                type: string
                format: date
                example: "2018-06-12T09:01:44Z"
            # "page_path" and "page_url" property
            path:
                type: string
                example: "/project/42"
            # "is_a" property
            category:
                type: array
                items:
                    type: string
                minItems: 1
                example: ["text", "article"]
            properties:
                type: object
            # edges include all properties but edges
            edges:
              type: array
              items:
                type: object
                properties:
                    predicate:
                      type: string
                    resource:
                      $ref: '#/definitions/Resource'
            media:
              type: array
              items:
                $ref: '#/definitions/Media'
        required:
            - id
            - title
            - body
            - summary
            - publication_date
            - path
            - category
            - properties
    Translation:
        type: object
        properties:
            en:
                type: string
                example: "Hello world"
            nl:
                type: string
                example: "Hallo wereld"
        minProperties: 1
    Media:
        type: object
        properties:
            url:
                type: string
                example: "http://example.org/images/foo.gif"
            mediaclass:
                type: string
                example: "thumbnail"

paths:
    /resources:
        get:
            produces: ["application/json"]
            description: "Get multiple resources"
            parameters:
                - in: query
                  name: cat
                  type: string
                  required: false
                  description: A category name
                - in: query
                  name: hasobject
                  type: string
                  required: false
                  description: A predicate name (of an outgoing edge)
                - in: query
                  name: hassubject
                  type: string
                  required: false
                  description: A predicate name (of an incoming edge)
            responses:
                200:
                    description: A list of resources
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Resource'
        post:
            consumes: ["application/json"]
            description: "Create a resource"
            parameters:
                - in: body
                  schema:
                      type: object
                      properties:
                          title:
                              $ref: '#/definitions/Translation'
                              required: false
                          body:
                              $ref: '#/definitions/Translation'
                              required: false
                          summary:
                              $ref: '#/definitions/Translation'
                              required: false
                          category:
                              type: string
                              description: "A Ginger category"
                              required: true
                          properties:
                              type: string
                              description: "Properties that are not included in the default REST GET response"
                              required: falses

    /resources/{id}:
        get:
            produces: ["application/json"]
            description: "Get a single resource by id"
            parameters:
                - in: path
                  name: id
                  type: integer
                  required: true
            responses:
                200:
                    description: A resource
                    schema:
                        $ref: '#/definitions/Resource'

    /resources/{id}/edges/{predicate}:
        post:
            consumes: ["application/json"]
            description: "Create edges"
            parameters:
                - in: path
                  name: id
                  type: integer
                  required: true
                  description: the ID of the subject
                - in: path
                  name: predicate
                  type: string
                  required: true
                  description: the name of the predicate
                - in: body
                  schema:
                      type: object
                      properties:
                          object:
                              type: integer
                              description: the ID of the object

    /resources/path/{path}:
        get:
            produces: ["application/json"]
            description: "Get a single resource by path"
            parameters:
                - in: path
                  name: path
                  type: string
                  required: true
            responses:
                200:
                    description: A resource
                    schema:
                        $ref: '#/definitions/Resource'

    /search:
        get:
            produces: ["application/json"]
            description: "Search resources"
            parameters:
                - in: query
                  name: text
                  type: string
                  required: false
                  description: Textual search query.
                - in: query
                  name: cat
                  type: string
                  required: false
                  description: Include resources of this category in the result.
                - in: query
                  name: cat_exclude
                  type: string
                  required: false
                  description: Exclude resources of this category from the result.
                - in: query
                  name: cat_promote
                  type: string
                  required: false
                  description: Boost result ranking for resources that are in specific categories.
                - in: query
                  name: cat_promote_recent
                  type: string
                  required: false
                  description: Boost result ranking for recently published resources that are in specific categories.
                - in: query
                  name: content_group
                  type: string
                  required: false
                  description: Only return search results that are in this content group (unique name or id).
                - in: query
                  name: has_geo
                  type: string
                  required: false
                  description: Only return search results that have geo coordinates (latitude and longitude).
                - in: query
                  name: offset
                  type: integer
                  required: false
                  description: Offset the list of search results.
                  default: 0
                - in: query
                  name: limit
                  type: integer
                  required: false
                  description: Limit the list of search results.
                  default: 1000
                - in: query
                  name: facet
                  type: string
                  required: false
                  description: Return facet for a property in the search results (`facet=date_start`).
                - in: query
                  name: filter
                  type: string
                  required: false
                  description: Filter search results by a property (`filter=title=Oh yeah`, `filter=date_start>=2000-01-01`).
                - in: query
                  name: sort
                  type: string
                  required: false
                  description: Property to search results on. Prepend with `-` for descending sort.
                - in: query
                  name: type
                  type: string
                  required: false
                  default: 'ginger_search'
                  description: The search type.
                - in: query
                  name: unfinished
                  type: string
                  required: false
                  description: Only return search results that have a date_end in the future.
                - in: query
                  name: upcoming
                  type: string
                  required: false
                  description: Only return search results that have a date_start in the future.
            responses:
                200:
                    description: Search results.
                    schema:
                        type: object
                        properties:
                            result:
                                type: array
                                items:
                                    $ref: '#/definitions/Resource'
                            total:
                                type: integer
                                description: 'The total number of search results.'
                                example: 42
                            facets:
                                type: array
                                description: 'The search result facets (aggregations).'
