swagger: "2.0"
info:
    title: "Ginger REST API documentation"
    description: "Documentation for the Ginger REST API"
    version: 0.1

host: DOMAIN
basePath: "/data"
schemes:
    - http
    - https

paths:
    /resources:
        get:
            parameters:
                - in: query
                  name: cat
                  type: string
                  required: false
                  description: A category name
                - in: query
                  name: hasobject
                  type: string
                  required: false
                  description: A predicate name (of an outgoing edge)
                - in: query
                  name: hassubject
                  type: string
                  required: false
                  description: A predicate name (of an incoming edge)
    /resources/{id}:
        get:
            parameters:
                - in: path
                  type: integer
                  required: true
    /resources/{id}/incoming-edges:
        get:
            parameters:
                - in: path
                  type: integer
                  required: true
    /resources/path/{path}:
        get:
            parameters:
                - in: path
                  type: string
                  required: true
